spring:
  application:
    name: BackendClassEx

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://to-on.kr:3306/hanyang5?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: to_on_admin
    password: BgCt9kuMws9jOivFj05UcEYpauecNa076H0oontnNrUGgG13lr


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml

server:
  port: 3301



